### ISSUE TITLE
How to execute custom model and custom function?

### ISSUE THREAD

**Issue by akira32chen** [sauljabin/xmlrpcwsc-dotnet#5]
How to execute custom model and custom function?
like the python as below:
```
models.execute_kw(db, uid, password,
    'res.partner', 'check_access_rights',
    ['read'], {'raise_exception': False})
```

**Comment by fjarboleda-lm** [comment]
Here you are...

`            XmlRpcClient client = new XmlRpcClient();
            client.Url = Url;
            client.Path = "object";

            var array_read = XmlRpcParameter.AsArray("read");   // ['read']
            var raise_param = XmlRpcParameter.AsStruct(         // {'raise_exception': False}
                                XmlRpcParameter.AsMember("raise_exception", false));

            XmlRpcRequest request = new XmlRpcRequest("execute_kw");
            request.AddParams(db, uid, pasword, "res.partner", "check_access_rights",
                                                            array_read, raise_param );

            XmlRpcResponse response = client.Execute(request);

            if (response.IsFault())
            { ...
`

**Comment by sauljabin** [comment]
thanks @fjarboleda-lm
